# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://ab.dgmc.tech/users")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Test322")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test@test.com")
    self.driver.find_element(By.CSS_SELECTOR, ".select2-selection__placeholder").click()
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search--dropdown > .select2-search__field").send_keys("salix")
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search--dropdown > .select2-search__field").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".custom-control-label").click()
    self.driver.find_element(By.ID, "user_password").click()
    self.driver.find_element(By.ID, "user_password").send_keys("Test1234")
    self.driver.find_element(By.ID, "user_password_confirm").click()
    self.driver.find_element(By.ID, "user_password_confirm").send_keys("Test1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even > td:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
  
